# ==========================================================================
# W-O-EN-01  |  W-O-EN-01 ABTS Activity Assay
# Auto-generated from the literate notebook - edit PARAMETERS in the
# notebook and re-generate; do not hand-edit this file.
# ==========================================================================

from opentrons import protocol_api

metadata = {'protocolName': 'W-O-EN-01 ABTS Activity Assay', 'author': 'iGEM 2026 DTU', 'source': 'Generated by W-O-EN-01 literate notebook', 'description': 'ThermoFisher T-AOC ABTS reagent additions (peroxidase + ABTS working solution) + mix + 6 min develop; samples pre-loaded; read A414 off-deck.'}
requirements = {"robotType": "OT-2", "apiLevel": '2.16'}

# ==========================================================================
# PARAMETERS  (single source of truth - generated from the notebook)
# ==========================================================================
P300_MODEL = 'p300_multi_gen2'
P20_MODEL = 'p20_multi_gen2'
P300_MOUNT = 'left'
P20_MOUNT = 'right'
ASSAY_PLATE_LOADNAME = 'corning_96_wellplate_360ul_flat'  # clear flat-bottom for A414
RESERVOIR_LOADNAME = 'nest_12_reservoir_15ml'
TIPRACK_300_LOADNAME = 'opentrons_96_tiprack_300ul'
TIPRACK_20_LOADNAME = 'opentrons_96_tiprack_20ul'
ASSAY_PLATE_SLOT = 2
TIPRACK_300_SLOT = 4
RESERVOIR_SLOT = 5
TIPRACK_20_SLOT = 6
NUM_SAMPLE_COLUMNS = 10  # PLACEHOLDER (1-12)
PEROXIDASE_RESERVOIR_WELL = 'A1'
ABTS_RESERVOIR_WELL = 'A2'
PEROXIDASE_VOL_UL = 20
ABTS_VOL_UL = 170
MIX_REPS = 3
MIX_VOL_UL = 100
DEVELOP_MIN = 6
PEROXIDASE_NEW_TIP_PER_COLUMN = False
ABTS_NEW_TIP_PER_COLUMN = True

def run(ctx: protocol_api.ProtocolContext):

    # ---- Deck, labware, instruments ----
    assay_plate = ctx.load_labware(ASSAY_PLATE_LOADNAME, ASSAY_PLATE_SLOT)
    tiprack_300 = ctx.load_labware(TIPRACK_300_LOADNAME, TIPRACK_300_SLOT)
    reservoir   = ctx.load_labware(RESERVOIR_LOADNAME, RESERVOIR_SLOT)
    tiprack_20  = ctx.load_labware(TIPRACK_20_LOADNAME, TIPRACK_20_SLOT)
    p300 = ctx.load_instrument(P300_MODEL, P300_MOUNT, tip_racks=[tiprack_300])
    p20  = ctx.load_instrument(P20_MODEL,  P20_MOUNT,  tip_racks=[tiprack_20])

    sample_cols = [assay_plate[f"A{c}"] for c in range(1, NUM_SAMPLE_COLUMNS + 1)]

    # ---- U-O-01: Add peroxidase application solution ----
    p20.transfer(
        PEROXIDASE_VOL_UL,
        reservoir[PEROXIDASE_RESERVOIR_WELL],
        sample_cols,
        new_tip=("always" if PEROXIDASE_NEW_TIP_PER_COLUMN else "once"),
    )

    # ---- U-O-02: Add ABTS working solution + mix ----
    p300.transfer(
        ABTS_VOL_UL,
        reservoir[ABTS_RESERVOIR_WELL],
        sample_cols,
        new_tip=("always" if ABTS_NEW_TIP_PER_COLUMN else "once"),
        mix_after=(MIX_REPS, MIX_VOL_UL),
    )

    # ---- U-O-03: Stand 6 min (develop) ----
    ctx.delay(minutes=DEVELOP_MIN)

    # ---- U-C-01: Hand off to Clariostar (414 nm) ----
    ctx.pause("U-C-01: Remove the plate and read A414 on the Clariostar.")
