# ==========================================================================
# W-O-SC-01  |  W-O-SC-01 NNBT Purpald HTS
# Auto-generated from the literate notebook - edit PARAMETERS in the
# notebook and re-generate; do not hand-edit this file.
# ==========================================================================

from opentrons import protocol_api

metadata = {'protocolName': 'W-O-SC-01 NNBT Purpald HTS', 'author': 'iGEM 2026 DTU', 'source': 'Generated by W-O-SC-01 literate notebook', 'description': 'NNBT colorimetric HTS reagent additions + heater-shaker development; samples pre-loaded; read A530 off-deck.'}
requirements = {"robotType": "OT-2", "apiLevel": '2.16'}

# ==========================================================================
# PARAMETERS  (single source of truth - generated from the notebook)
# ==========================================================================
P300_MODEL = 'p300_multi_gen2'
P20_MODEL = 'p20_multi_gen2'
P300_MOUNT = 'left'
P20_MOUNT = 'right'
ASSAY_PLATE_LOADNAME = 'corning_96_wellplate_360ul_flat'  # clear flat-bottom for A530
RESERVOIR_LOADNAME = 'nest_12_reservoir_15ml'
TIPRACK_300_LOADNAME = 'opentrons_96_tiprack_300ul'
TIPRACK_20_LOADNAME = 'opentrons_96_tiprack_20ul'
HS_SLOT = 1  # Heater-Shaker + assay plate
TIPRACK_300_SLOT = 4  # behind HS (tip rack allowed)
RESERVOIR_SLOT = 5  # diagonal to HS
TIPRACK_20_SLOT = 6
NUM_SAMPLE_COLUMNS = 10  # PLACEHOLDER (1-12)
NNBT_MIX_RESERVOIR_WELL = 'A1'
PURPALD_RESERVOIR_WELL = 'A2'
NNBT_MIX_VOL_UL = 50
PURPALD_VOL_UL = 50
NNBT_INCUBATION_TEMP_C = 30  # ambient on OT-2 if <37
NNBT_SHAKE_RPM = 800
NNBT_INCUBATION_MIN = 5
DEVELOP_SHAKE_RPM = 800
DEVELOP_MIN = 10
NEW_TIP_PER_COLUMN = False

def run(ctx: protocol_api.ProtocolContext):

    # ---- Deck, labware, instruments ----
    hs_mod = ctx.load_module("heaterShakerModuleV1", HS_SLOT)
    assay_plate = hs_mod.load_labware(ASSAY_PLATE_LOADNAME)
    tiprack_300 = ctx.load_labware(TIPRACK_300_LOADNAME, TIPRACK_300_SLOT)
    reservoir   = ctx.load_labware(RESERVOIR_LOADNAME, RESERVOIR_SLOT)
    tiprack_20  = ctx.load_labware(TIPRACK_20_LOADNAME, TIPRACK_20_SLOT)
    p300 = ctx.load_instrument(P300_MODEL, P300_MOUNT, tip_racks=[tiprack_300])
    p20  = ctx.load_instrument(P20_MODEL,  P20_MOUNT,  tip_racks=[tiprack_20])

    sample_cols = [assay_plate[f"A{c}"] for c in range(1, NUM_SAMPLE_COLUMNS + 1)]
    hs_mod.close_labware_latch()  # secure plate for pipetting + shaking

    # ---- U-O-01: Add NNBT reaction mix ----
    p300.transfer(
        NNBT_MIX_VOL_UL,
        reservoir[NNBT_MIX_RESERVOIR_WELL],
        sample_cols,
        new_tip=("always" if NEW_TIP_PER_COLUMN else "once"),
    )

    # ---- U-O-02: Seal -> shake-incubate (NNBT) -> unseal ----
    ctx.pause("U-O-02: SEAL the plate, then resume to shake-incubate.")
    if NNBT_INCUBATION_TEMP_C >= 37:
        hs_mod.set_and_wait_for_temperature(NNBT_INCUBATION_TEMP_C)
    else:
        ctx.comment("NNBT_INCUBATION_TEMP_C < 37 C: OT-2 HS cannot heat; shaking at ambient.")
    hs_mod.set_and_wait_for_shake_speed(NNBT_SHAKE_RPM)
    ctx.delay(minutes=NNBT_INCUBATION_MIN)
    hs_mod.deactivate_shaker()
    if NNBT_INCUBATION_TEMP_C >= 37:
        hs_mod.deactivate_heater()
    ctx.pause("U-O-02 done: UNSEAL the plate, then resume.")

    # ---- U-O-03: Add Purpald reagent ----
    p300.transfer(
        PURPALD_VOL_UL,
        reservoir[PURPALD_RESERVOIR_WELL],
        sample_cols,
        new_tip=("always" if NEW_TIP_PER_COLUMN else "once"),
    )

    # ---- U-O-04: Seal -> shake to develop -> unseal ----
    ctx.pause("U-O-04: SEAL the plate, then resume to develop colour.")
    hs_mod.set_and_wait_for_shake_speed(DEVELOP_SHAKE_RPM)
    ctx.delay(minutes=DEVELOP_MIN)
    hs_mod.deactivate_shaker()
    ctx.pause("U-O-04 done: UNSEAL the plate, then resume.")

    # ---- U-C-01: Hand off to Clariostar (530 nm) ----
    hs_mod.open_labware_latch()
    ctx.pause("U-C-01: Remove the plate and read A530 on the Clariostar.")
