#!/usr/bin/env python3
"""Batch-run fpocket on every PDB or mmCIF file in a directory.

fpocket creates <stem>_out/ next to the input file; this script moves each
result folder into the output directory so inputs stay clean.

Examples
--------
    python3 run_fpocket.py inputs/
    python3 run_fpocket.py inputs/ -o outputs/ --overwrite
    python3 run_fpocket.py /path/to/pdb_folder -o /path/to/results
"""
import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
VENDORED_FPOCKET = SCRIPT_DIR / "fpocket" / "bin" / "fpocket"


def default_fpocket() -> str:
    """Locate an fpocket binary that works on this platform.

    Prefers one on PATH (e.g. installed via `conda install -c bioconda fpocket`,
    which works on Linux and macOS) so the pipeline is cross-platform. Falls back
    to the vendored Linux binary only if nothing is on PATH.
    """
    on_path = shutil.which("fpocket")
    if on_path:
        return on_path
    return str(VENDORED_FPOCKET)


def _fpocket_input(src: Path) -> tuple[Path, Path | None]:
    """Return (file_to_pass_to_fpocket, tmp_dir_to_clean_up_or_None).

    fpocket's format detector triggers its CIF parser whenever the filename
    contains '.cif', even when '.cif' appears in the stem rather than as the
    extension (e.g. 'design.cif_b0_d0.pdbqt'). This causes a parse failure on
    PDB-format content. The workaround is to copy to a temp file whose name is
    free of '.cif'.

    For CIF sources the PDBQT (generated by prepare_receptor.py) is preferred
    because fpocket's built-in CIF parser does not handle all mmCIF variants.
    """
    # Prefer PDBQT over raw CIF
    if src.suffix.lower() == ".cif":
        pdbqt = src.with_suffix(".pdbqt")
        src = pdbqt if pdbqt.exists() else src

    # If the filename still contains '.cif', copy to a sanitised temp name
    if ".cif" in src.name:
        tmp_dir = Path(tempfile.mkdtemp())
        safe_name = src.stem.replace(".", "_") + ".pdb"
        tmp_file = tmp_dir / safe_name
        shutil.copy2(str(src), str(tmp_file))
        return tmp_file, tmp_dir

    return src, None


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("input_dir", help="Directory containing .pdb or .cif files")
    p.add_argument(
        "-o", "--output_dir",
        default=str(SCRIPT_DIR / "outputs"),
        help="Where to save the fpocket _out/ folders (default: outputs/)",
    )
    p.add_argument(
        "--fpocket",
        default=default_fpocket(),
        help="Path to fpocket binary (default: fpocket on PATH, else the "
             "vendored fpocket/bin/fpocket)",
    )
    p.add_argument(
        "--overwrite", action="store_true",
        help="Re-run fpocket even if the output folder already exists",
    )
    args = p.parse_args()

    fpocket_bin = Path(args.fpocket).resolve()
    if not fpocket_bin.is_file():
        sys.exit(
            f"fpocket binary not found: {fpocket_bin}\n"
            f"Install it (cross-platform):  conda install -c bioconda fpocket\n"
            f"or build from source:         cd fpocket && make"
        )

    input_dir = Path(args.input_dir).resolve()
    if not input_dir.is_dir():
        sys.exit(f"Input directory not found: {input_dir}")

    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    pdb_files = sorted(input_dir.glob("*.pdb")) + sorted(input_dir.glob("*.cif"))
    if not pdb_files:
        sys.exit(f"No .pdb or .cif files found in {input_dir}")

    print(f"Input  : {input_dir}  ({len(pdb_files)} file(s))")
    print(f"Output : {output_dir}\n")

    failed = []
    for src in pdb_files:
        stem = src.stem
        out_name = f"{stem}_out"
        dest = output_dir / out_name

        if dest.exists() and not args.overwrite:
            print(f"[SKIP] {src.name}  ({out_name}/ exists — use --overwrite to redo)")
            continue

        fpocket_input, tmp_dir = _fpocket_input(src)

        print(f"[RUN ] {src.name} ...", end="", flush=True)
        result = subprocess.run(
            [str(fpocket_bin), "-f", str(fpocket_input)],
            capture_output=True,
            text=True,
        )

        # fpocket writes <fpocket_input.stem>_out/ next to the input file
        created = fpocket_input.parent / f"{fpocket_input.stem}_out"

        if result.returncode != 0 or not created.exists():
            print(" FAILED")
            if result.stderr.strip():
                print(f"       {result.stderr.strip()}")
            elif result.stdout.strip():
                print(f"       {result.stdout.strip()}")
            failed.append(src.name)
        else:
            if dest.exists():
                shutil.rmtree(dest)
            shutil.move(str(created), str(dest))
            try:
                label = dest.relative_to(SCRIPT_DIR)
            except ValueError:
                label = dest
            print(f" done  → {label}/")

        if tmp_dir and tmp_dir.exists():
            shutil.rmtree(str(tmp_dir))

    print()
    if failed:
        print(f"Failed ({len(failed)}): {', '.join(failed)}")
        sys.exit(1)
    print("All done.")


if __name__ == "__main__":
    main()
